$(window).scroll(function(){
if($(window).scrollTop()>10){
    $(".header").addClass("active")
}
else{
    $(".header").removeClass("active")
}
})

$(document).ready(function(){
    $(window).scroll(function(){
        if($(window).scrollTop>50){
            $("#myBtn").fadeIn()
        }
        else{
            $("#myBtn").fadeOut()
        }
    })
})